#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S2,     gyro,                sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     htproto,             sensorI2CCustom9V)
#pragma config(Motor,  motorA,          rightArmSpin,  tmotorNormal, openLoop, encoder)
#pragma config(Motor,  motorB,          leftArmSpin,   tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     rightDrive,    tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     armClaw,       tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     armWrist,      tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     ballCollector, tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     leftDrive,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     armBase,       tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define GYRO S2
#include "autonoLib.c"

#include "JoystickDriver.c"

bool leftPressed()
{
	static int cyclesUnpressed = 0;
	
	if ( nNxtButtonPressed == kLeftButton && cyclesUnpressed > 2000 )
    {
    	cyclesUnpressed = 0;
		return true;
    }
	else if ( cyclesUnpressed < 4000 ) cyclesUnpressed++;
	
	return false;
}

bool rightPressed()
{
	static int cyclesUnpressed = 0;
	
	if ( nNxtButtonPressed == kRightButton && cyclesUnpressed > 2000 )
    {
    	cyclesUnpressed = 0;
		return true;
    }
	else if ( cyclesUnpressed < 4000 ) cyclesUnpressed++;
	
	return false;
}

int getValueFromUser(string s = "Value", int max = 10, int min = 0)
{
	int m_val = min;
	while(1)
	{
		nxtDisplayString(0, "%s: %i", s, m_val);
		if ( rightPressed() )
			m_val++;
		else if ( leftPressed() )
			m_val--;
		
		if ( nNxtButtonPressed == kEnterButton )
			return m_val;
	}
}

int getDelay()
{
  int m_delay=0;
  int cyclesUnpressed = 0;
  while(1)
  {
    nxtDisplayString(0, "Delay: %i", m_delay);
    if ( nNxtButtonPressed == kRightButton && cyclesUnpressed > 2000 )
    {
      m_delay++;
      cyclesUnpressed = 0;
    }
    else if ( nNxtButtonPressed == kLeftButton && cyclesUnpressed > 2000 )
    {
      m_delay--;
      cyclesUnpressed = 0;
    }
    else if ( nNxtButtonPressed == kEnterButton )
      return m_delay;
    else if ( cyclesUnpressed < 3000 ) cyclesUnpressed++;

    if ( m_delay < 0 ) m_delay = 0;
  }
  return 0;
}


task main()
{
  int delay  = getDelay();
  wait1Msec(800);
  int autoID = selectAuton();

  wait1Msec(delay*1000);

  switch ( autoID )
  {
  case 1:
    nxtDisplayString(0, "Straight");
    break;
  case 2:
    nxtDisplayString(0, "RedFarPark");
    break;
  case 3:
    nxtDisplayString(0, "BluFarPark");
    break;
  default:
    nxtDisplayString(0, "Invalid ID");
    wait1Msec(2000);
    return;
    break;
  }

  initGyro();
  waitForStart();
  wait1Msec(delay*1000);
  switch ( autoID )
  {
    case 1:
      frontPark();
      break;
    case 2:
      redFarPark();
      break;
    case 3:
      bluFarPark();
      break;
  }

  while(1) continue;
}
